name: email-nodejs-project

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
        
      - name: setup docker-build
        uses: docker/setup-buildx-action@v2

      - name: Print environment variables
        run: env
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: Joeprogrammer69/simplerepo:latest
        
  send-email:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: hilarion5/send-mail@v1
        with:
          server_address: smtp.example.com
          server_port: 25
          from: your-email@example.com
          to: your-email@example.com
          subject: Docker Image Build Notification
          body: The Docker image has been successfully built and published.
